### ISSUE TITLE
Social Media Icons and Navbar Links

### ISSUE THREAD

**Issue by saumyayadav25** [Code-Social/official-website#152]
**Describe the bug**
Social Media Icon in the website are images, it will be better if you use fonts-awesome (fa) for social links and icons for better view.

**Expected behavior**
The icons should align with each other.

**Screenshots**
(similarly for footer section)
<img width="562" alt="Screenshot 2024-10-11 at 6 20 00 PM" src="https://github.com/user-attachments/assets/df02e85f-b0fe-4b81-9763-48f25eeb8f64">

**Desktop (please complete the following information):**
 - OS: macOs
 - Browser: chrome

**Additional context**
Navbar links don't have proper styling due to which they are not visible properly.

**Comment by Diya-Saha2005** [comment]
Hello project admin ! I found bugs in the navbar. The links are not visible enough and the overall navbar needs styling . Since I would like to contribute to this project , I request you to assign it to me.
![Screenshot (364)](https://github.com/user-attachments/assets/230d2c40-0172-40bc-883a-c474b8587dfd)

**Comment by saumyayadav25** [comment]
@pulkitpathak99 kindly review this issue.
